import { PostStyle } from "../types";

export const stylePresets: PostStyle[] = [
  {
    name: "Kevin Dumont",
    background: {
      type: "gradient",
      color: "#4338ca",
      gradientColor: "#7e22ce",
      gradientDirection: "to bottom right",
      gradientType: "linear",
      accentColor: "#ffd700",
      imageDarkness: 0.3,
    },
    titleSize: 32,
    itemTitleSize: 20,
    descriptionSize: 16,
    footerSize: 16,
    footerSubtitleSize: 14,
    itemSpacing: 24,
    itemPadding: {
      top: 17,
      right: 24,
      bottom: 24,
      left: 41,
    },
    contentPadding: {
      top: 32,
      right: 32,
      bottom: 32,
      left: 32,
    },
    footerPadding: {
      top: 16,
      right: 16,
      bottom: 16,
      left: 16,
    },
    titleDescriptionSpacing: 12,
    itemNumberSize: 72,
    showItemNumbers: true,
    itemNumberStyle: {
      backgroundColor: "#ffffff",
      opacity: 0,
      showBorder: false,
      borderWidth: 1,
      borderColor: "#ffffff",
      borderRadius: 16,
      padding: 16,
      fixedSize: true,
      width: 60,
      height: 60,
    },
    font: "'Roboto', sans-serif",
    footer: {
      name: "Kevin Dumont",
      subtitle: "@k_dumont",
      photoUrl: "",
      rightText: "Vous avez aimé ? *Republiez ↻*",
    },
    colors: {
      title: "#ffffff",
      itemTitle: "#ffffff",
      description: "#ffffff",
      itemNumber: "#ffffff",
      footerName: "#ffffff",
      footerSubtitle: "#ffffff",
      footerRight: "#ffffff",
    },
    card: {
      backgroundColor: "#ffffff",
      opacity: 0.1,
      showBorder: false,
      borderWidth: 1,
      borderColor: "#ffffff",
      borderRadius: 8,
    },
  },
  {
    name: "Ruben Taieb",
    background: {
      type: "solid",
      color: "#121212",
      gradientColor: "#7e22ce",
      gradientDirection: "to bottom right",
      gradientType: "linear",
      accentColor: "#ffffff",
      imageDarkness: 0.3,
    },
    titleSize: 31,
    itemTitleSize: 19,
    descriptionSize: 15,
    footerSize: 15,
    footerSubtitleSize: 14,
    itemSpacing: 24,
    itemPadding: {
      top: 15,
      right: 24,
      bottom: 24,
      left: 35,
    },
    contentPadding: {
      top: 32,
      right: 32,
      bottom: 32,
      left: 32,
    },
    footerPadding: {
      top: 16,
      right: 16,
      bottom: 16,
      left: 16,
    },
    titleDescriptionSpacing: 12,
    itemNumberSize: 24,
    showItemNumbers: true,
    itemNumberStyle: {
      backgroundColor: "#000000",
      opacity: 1,
      showBorder: true,
      borderWidth: 1,
      borderColor: "#ffffff",
      borderRadius: 100,
      padding: 11,
      fixedSize: true,
      width: 38,
      height: 38,
    },
    font: "'Inter', sans-serif",
    footer: {
      name: "Ruben Taieb",
      subtitle: "+100K abonnés",
      photoUrl: "",
      rightText: "Je partage un conseil LinkedIn par jour",
    },
    colors: {
      title: "#ffffff",
      itemTitle: "#ffffff",
      description: "#ffffff",
      itemNumber: "#ffffff",
      footerName: "#ffffff",
      footerSubtitle: "#ffffff",
      footerRight: "#ffffff",
    },
    card: {
      backgroundColor: "#000000",
      opacity: 1,
      showBorder: true,
      borderWidth: 1,
      borderColor: "#ffffff",
      borderRadius: 13,
    },
  },
  {
    name: "Vibrant",
    background: {
      type: "gradient",
      color: "#f97316",
      gradientColor: "#db2777",
      gradientDirection: "to bottom left",
      gradientType: "linear",
      accentColor: "#22d3ee",
      imageDarkness: 0.3,
    },
    titleSize: 32,
    itemTitleSize: 18,
    descriptionSize: 16,
    footerSize: 16,
    footerSubtitleSize: 14,
    itemSpacing: 20,
    itemPadding: {
      top: 20,
      right: 20,
      bottom: 20,
      left: 20,
    },
    contentPadding: {
      top: 32,
      right: 32,
      bottom: 32,
      left: 32,
    },
    footerPadding: {
      top: 16,
      right: 16,
      bottom: 16,
      left: 16,
    },
    titleDescriptionSpacing: 12,
    itemNumberSize: 42,
    showItemNumbers: false,
    itemNumberStyle: {
      backgroundColor: "#ffffff",
      opacity: 0.2,
      showBorder: false,
      borderWidth: 1,
      borderColor: "#ffffff",
      borderRadius: 12,
      padding: 12,
      fixedSize: false,
      width: 50,
      height: 50,
    },
    font: "'Poppins', sans-serif",
    footer: {
      name: "Votre Nom",
      subtitle: "Votre titre",
      photoUrl: "",
      rightText: "Vous avez aimé ? *Partagez ↻*",
    },
    colors: {
      title: "#ffffff",
      itemTitle: "#ffffff",
      description: "#ffffff",
      itemNumber: "#ffffff",
      footerName: "#ffffff",
      footerSubtitle: "#ffffff",
      footerRight: "#ffffff",
    },
    card: {
      backgroundColor: "#000000",
      opacity: 0.2,
      showBorder: false,
      borderWidth: 1,
      borderColor: "#ffffff",
      borderRadius: 8,
    },
  },
];